name: 'Upload Artifacts'
description: 'Upload build artifacts to GitHub'

runs:
  using: 'composite'
  steps:
    - name: Rename APK files
      shell: bash
      run: |
        mkdir -p artifacts
        VERSION="${{ env.PACKAGE_VERSION }}"
        echo "Package version: $VERSION"
        
        # 复制并重命名APK文件
        if [ -d "app/build/outputs/apk/release" ]; then
          cd app/build/outputs/apk/release
          
          # 处理APK文件
          for apk in *.apk; do
            if [[ "$apk" == *"arm64-v8a"* ]]; then
              cp "$apk" "../../../../artifacts/weather-app-v${VERSION}-arm64-v8a.apk"
            elif [[ "$apk" == *"armeabi-v7a"* ]]; then
              cp "$apk" "../../../../artifacts/weather-app-v${VERSION}-armeabi-v7a.apk"
            elif [[ "$apk" == *"x86_64"* ]]; then
              cp "$apk" "../../../../artifacts/weather-app-v${VERSION}-x86_64.apk"
            elif [[ "$apk" == *"x86"* ]]; then
              cp "$apk" "../../../../artifacts/weather-app-v${VERSION}-x86.apk"
            else
              cp "$apk" "../../../../artifacts/weather-app-v${VERSION}-universal.apk"
            fi
          done
        else
          echo "APK output directory not found in app/build/outputs/apk/release"
          # 尝试搜索其他位置
          find . -name "*.apk" | while read apk; do
            echo "Found APK at: $apk"
            cp "$apk" "../../../../artifacts/weather-app-v${VERSION}-universal.apk"
          done
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apk-files
        path: artifacts/*.apk
