name: Android Hello World Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发工作流

# 添加必要的权限
permissions:
  contents: write
  packages: write
  
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: List project files
        run: ls -la
        
      - name: Build with Gradle
        run: ./gradlew assembleDebug --info
        
      - name: List APK directory
        run: find . -name "*.apk"
        
      - name: Rename APK
        run: |
          mkdir -p release
          find app/build/outputs/apk/debug -name "*.apk" -exec cp {} release/hello-world-app.apk \;
      
      - name: Generate Release Timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
        
      - name: Extract version from update file
        id: version_info
        run: |
          VERSION=$(head -n 1 app/updat/updat.md)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          cat app/updat/updat.md > ./release_notes.md
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version_info.outputs.version || format('v{0}', steps.timestamp.outputs.timestamp) }}
          name: 天气预报应用 ${{ steps.version_info.outputs.version || format('Build {0}', steps.timestamp.outputs.timestamp) }}
          body_path: ./release_notes.md
          files: release/hello-world-app.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 